nova_bot: "wish nature safe affair picture march shoe naive dumb high clay north grief appear visit destroy motor weasel patch option safe alone art banner"
atom_bot: "excite dash rail pony prepare damp supply rural adjust bid spoil lake method sell iron bar unique source orient panther aisle jungle hazard giraffe"
nova_fake_bot: "dragon parrot brush siege marine stock affair oblige bottom beef oak wolf honey shove parade pupil aisle enjoy saddle try combine tree fluid awake"

pw: dlwotmdqht